version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  nodejs:
    build: .
    container_name: nodejs-container
    ports:
      - "8000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/testDocker?authSource=admin
    volumes:
      - .:/app
    command: npm start

volumes:
  mongo-data:
